spring:
  cloud:
    gateway:
      routes:
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/ware?(?<segment>.*),/gulimalware/$\{segment}
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/product?(?<segment>.*),/gulimalProduct/$\{segment}
        - id: member-route
          uri: lb://gulimal-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/member?(?<segment>.*),/gulimalmember/$\{segment}
        - id: coupon-route
          uri: lb://gulimal-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/coupon?(?<segment>.*),/gulimalcoupon/$\{segment}
        - id: third_party_route
          uri: lb://gulimall-third-part
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*),/$\{segment}
        - id: admin_route
          uri:  lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}
        - id: gulimall_host_route
          uri:  lb://gulimall-product
          predicates:
            - Host=**.gulimall.com

